fix -  update nutpie version to 0.16.5
This fixes the error the
"RuntimeError: Coordinate batch_effect_dims value has unsupported type

Caused by:
    RuntimeError: Could not convert to Value. Unsupported type: ArrowStringArray"

see: https://discourse.pymc.io/t/runtimeerror-unsupported-type-arrowstringarray-during-nutpie-sample/17542